#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

version: 1.0
uown: eefa6898-cb13-4fd0-9a6f-ee3ff558888d #upinot
command: |
  export NODE_ENV=development; git checkout $BUILDKITE_BRANCH; if [ -f ".buildkite/release.sh" ]; then .buildkite/release.sh;else release_opts=;if [ -n "$RELEASE_VERSION" ]; then release_opts="$release_opts -DreleaseVersion=$RELEASE_VERSION"; fi; if [ -n "$NEXT_VERSION" ]; then release_opts="$release_opts -DdevelopmentVersion=$NEXT_VERSION"; fi; mvn -B release:clean release:prepare release:perform $release_opts; fi;
timeout_in_minutes: 300
